import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useSession } from "next-auth/react";

import { api } from "@/utils/api";
import { Header } from "@/components/Header";
import { Loader } from "@/components/Loader";
import { useState } from "react";
import type { Topic } from "@prisma/client";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Notaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Content />
    </>
  );
};

export default Home;

export const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);

  const {
    data: topics,
    refetch: refetchTopics,
    isLoading,
    isRefetching
  } = api.topic.getAll.useQuery(undefined, {
    enabled: !!sessionData?.user,
    refetchOnWindowFocus: false,
    onSuccess: (data) => {
      setSelectedTopic(selectedTopic ?? data[0] ?? null);
    }
  });


  const createTopic = api.topic.create.useMutation({
    onSuccess: () => {
      void refetchTopics();
    },
  });

  return (
    <main className="mx-5 mt-5 grid grid-cols-4 gap-2">
      <div>
         <ul className="menu rounded-box w-56 bg-base-100 p-2">
          {topics?.map((topic) => (
            <li key={topic.id}>
              <a
                href="#"
                onClick={(evt) => {
                  evt.preventDefault();
                  setSelectedTopic(topic);
                }}
              >
                {topic.title}
              </a>
            </li>
          ))}
        </ul>
        {isLoading || (isRefetching && <Loader />)}
        <div className="divider" />

        <input
          type="text"
          className="input-bordered input-secondary input w-full max-w-xs"
          placeholder="New topic..."
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              createTopic.mutate({ title: e.currentTarget.value });
              e.currentTarget.value = "";
            }
          }}
        />
      </div>
      <div className="col-span-3">hello</div>
    </main>
  );
};

